// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// myPoint
int myPoint(double x, double y, NumericVector vx, NumericVector vy);
RcppExport SEXP spatial_data_table_myPoint(SEXP xSEXP, SEXP ySEXP, SEXP vxSEXP, SEXP vySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vx(vxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vy(vySEXP);
    rcpp_result_gen = Rcpp::wrap(myPoint(x, y, vx, vy));
    return rcpp_result_gen;
END_RCPP
}
