# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppDistanceHaversine <- function(latFrom, lonFrom, latTo, lonTo, earthRadius, tolerance) {
    .Call('spatial_data_table_rcppDistanceHaversine', PACKAGE = 'spatial.data.table', latFrom, lonFrom, latTo, lonTo, earthRadius, tolerance)
}

