# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppAlongTrack <- function(latFrom, lonFrom, latTo, lonTo, pointLat, pointLon, tolerance, earthRadius) {
    .Call('spatial_data_table_rcppAlongTrack', PACKAGE = 'spatial.data.table', latFrom, lonFrom, latTo, lonTo, pointLat, pointLon, tolerance, earthRadius)
}

rcppDist2gc <- function(latFrom, lonFrom, latTo, lonTo, pointLat, pointLon, tolerance, earthRadius) {
    .Call('spatial_data_table_rcppDist2gc', PACKAGE = 'spatial.data.table', latFrom, lonFrom, latTo, lonTo, pointLat, pointLon, tolerance, earthRadius)
}

rcppDestination <- function(latFrom, lonFrom, distance, bearing, earthRadius) {
    .Call('spatial_data_table_rcppDestination', PACKAGE = 'spatial.data.table', latFrom, lonFrom, distance, bearing, earthRadius)
}

rcppMidpoint <- function(latFrom, lonFrom, latTo, lonTo) {
    .Call('spatial_data_table_rcppMidpoint', PACKAGE = 'spatial.data.table', latFrom, lonFrom, latTo, lonTo)
}

rcppBearing <- function(latFrom, lonFrom, latTo, lonTo, compassBearing) {
    .Call('spatial_data_table_rcppBearing', PACKAGE = 'spatial.data.table', latFrom, lonFrom, latTo, lonTo, compassBearing)
}

rcppDistanceHaversine <- function(latFrom, lonFrom, latTo, lonTo, earthRadius, tolerance) {
    .Call('spatial_data_table_rcppDistanceHaversine', PACKAGE = 'spatial.data.table', latFrom, lonFrom, latTo, lonTo, earthRadius, tolerance)
}

rcppDistanceCosine <- function(latFrom, lonFrom, latTo, lonTo, earthRadius) {
    .Call('spatial_data_table_rcppDistanceCosine', PACKAGE = 'spatial.data.table', latFrom, lonFrom, latTo, lonTo, earthRadius)
}

rcppClosePolygon <- function(polyVector) {
    .Call('spatial_data_table_rcppClosePolygon', PACKAGE = 'spatial.data.table', polyVector)
}

rcppIsPolygonClosed <- function(startX, endX, startY, endY) {
    .Call('spatial_data_table_rcppIsPolygonClosed', PACKAGE = 'spatial.data.table', startX, endX, startY, endY)
}

rcppPointsInPolygon <- function(pointsId, pointsX, pointsY, vectorX, vectorY) {
    .Call('spatial_data_table_rcppPointsInPolygon', PACKAGE = 'spatial.data.table', pointsId, pointsX, pointsY, vectorX, vectorY)
}

rcppWindingNumber <- function(pointX, pointY, vectorX, vectorY) {
    .Call('spatial_data_table_rcppWindingNumber', PACKAGE = 'spatial.data.table', pointX, pointY, vectorX, vectorY)
}

